#merge the branch with refactored codes with development branch
andela-uibrahim/inverted-index pull request #6
Opened 2017-03-01 14:13 UTC by andela-uibrahim

2017-03-10 18:39 UTC, andela-venogwe commented
hello, no description of what you did on these pull request to make it easier to review

2017-03-11 07:02 UTC, victor-enogwe requested changes

2017-03-11 07:02 UTC, victor-enogwe commented on .eslintignore
> +public/js/events.js
add jquery to eslint and lint this file

2017-03-11 07:02 UTC, victor-enogwe commented on .eslintrc
> +    "mocha": true
you don't use mocha on this project, change the eslint rule mocha true to one that complies with your testing framework

2017-03-11 07:02 UTC, victor-enogwe commented on karma.conf.js
>        'public/js/helper.js',
use file patterns to load files coming from the same directory and exclude the one you don't want loaded

2017-03-11 07:02 UTC, victor-enogwe commented on package.json
>    "engines": {
why specify node version and npm version in your app?

2017-03-11 07:02 UTC, victor-enogwe commented on public/css/styles.css
>  }
css rules are not properly aligned

2017-03-11 07:02 UTC, victor-enogwe commented on public/index.html
>  	<div class="row" id="top">
Fix empty divs in this file and use css rules to create all desired visual effects
lint your html properly

2017-03-11 07:02 UTC, victor-enogwe commented on public/js/InvertedIndexUI/controller.js
> +      if ($scope.indexedFiles === undefined) {
refactor if ($scope.indexedFiles === undefined) to if ($scope.indexedFiles)

2017-03-11 07:02 UTC, victor-enogwe commented on public/js/events.js
> +  $('#close').trigger('click');
arrow function not properly implemented, remove curly braces from functions that return only one statement.

2017-03-11 07:02 UTC, victor-enogwe commented on public/js/helper.js
> +        if ((doc.title === undefined) || (doc.text === undefined)) {
use negation instead of undefined

2017-03-11 07:02 UTC, victor-enogwe commented on public/templates/search.html
>  		</div>
lint your html file

2017-03-11 07:02 UTC, andela-venogwe commented on spec/InvertedIndex.spec.js
> +       [['alice', 'enters', 'a'], ['fellowship', 'wizard', 'on'],
you can put each arrays on separate lines

2017-03-13 09:38 UTC, andela-uibrahim commented on .eslintignore
> +public/js/events.js
@andela-venogwe  i have implemented this feedback

2017-03-13 09:39 UTC, andela-uibrahim commented on karma.conf.js
>        'public/js/helper.js',
@andela-venogwe  please can you shed more light on this?

2017-03-13 09:47 UTC, andela-venogwe commented on karma.conf.js
>        'public/js/helper.js',
okay, for files in the same directory you can use pattern matching to load them. eg. all files in './public' which have the js extension can be loaded like this './public/*.js'

2017-03-15 12:44 UTC, iAmao approved these changes

2017-03-15 12:44 UTC, andela-iamao commented on gulpfile.js
> +const Server = require('karma').Server;
Good job!

2017-03-15 12:44 UTC, andela-iamao commented on public/js/InvertedIndexUI/controller.js
> +      const reader = new FileReader();
I like that you used promises here! Nice one!

2017-03-15 12:44 UTC, andela-iamao commented on public/templates/searchContent.html
> +</div>
I think your html should not be an exception to the indentation rules.

2017-03-15 12:44 UTC, andela-iamao commented on spec/InvertedIndex.spec.js
> +     expect(helpers.validFileContent([{}])).toBe(false);
There are ways to write the specs without needing line breaks. Also it's not descriptive enough.
For example `should return boolean when invoked with +   ' a valid json file input` could be written as `should return true when passed a valid json file`

2017-03-17 14:12 UTC, merged